### ISSUE TITLE
Publishing a new minor version

### ISSUE THREAD

**Issue by petrochenkov** [crumblingstatue/rgmk#4]
Hi.
https://github.com/rust-lang/rust/pull/42125 is going to turn some old compatibility "private-in-public" warnings in `rustc` into hard errors.
`crates.io` testing discovered that published version of this crate is affected by one of those errors.
The current master is building successfully with https://github.com/rust-lang/rust/pull/42125, could you push it on crates.io as `rgmk-0.2.1`?

**Comment by crumblingstatue** [comment]
The master branch is under a from-scratch rewrite, it's not in a publishable state.

**Comment by crumblingstatue** [comment]
Also, I don't think anything depends on rgmk at this point.

**Comment by petrochenkov** [comment]
Ok, thanks for the quick answer.
We'll count this as a known/acceptable regression then.
